step 4
AndreyKrymski/frontend-project-lvl3 pull request #4
Opened 2022-08-26 19:46 UTC by AndreyKrymski

2022-08-31 14:12 UTC, sergeyivanov1702 requested changes

2022-08-31 14:12 UTC, sergeyivanov1702 commented on src/init.js
>        };
при создании state уже должны быть все поля, у тебя нехватает statusValidation и erorr.
statusValidation и isProcessing можно смело делать boolean, 
в начальном состоянии statusValidation = null, isProcessing = false.

2022-08-31 14:12 UTC, sergeyivanov1702 commented on src/elementsDom.js
>  export default {
этот файл исправишь со следующим степом. Тесты падают именно из-за него

2022-08-31 14:12 UTC, sergeyivanov1702 commented on src/init.js
> +              });
посмотри на этот код, нет ли рядом такого же?
подумай как будет работать код если убрать этот catch и выше упадет ошибка?

2022-08-31 14:12 UTC, sergeyivanov1702 commented on src/init.js
> +              });
сразу напишу ответ: если убрать этот, то ошибку обработает тот, который у тебя на 2 строчки ниже, а он с той же логикой

2022-08-31 14:12 UTC, sergeyivanov1702 commented on src/init.js
> +              .then((response) => {
then который работает с результатом запроса Get не обязательно должен быть вложенным. Вложенность обычно делает код сложнее.
Тут ты можешь делать это последоватьельно

```
validateUrl(value, state, i18nextInstance)
.then(() => axios.get(`https://allorigins.hexlet.app/get?url=${encodeURIComponent(url)}`))
.then((response) => {
...
...
})
.catch(...)
```

2022-08-31 14:12 UTC, sergeyivanov1702 commented on src/init.js
> +            state.erorr = '';
тут можно убрать `state.erorr = ''` ты выполняешь тот же код чуть ниже

2022-08-31 14:12 UTC, sergeyivanov1702 commented on src/init.js
> +                watcheState.isProcessing = 'processingCompleted';
`watcheState.isProcessing` обновляеться самый последний, когда уже все сделано.
Это обновление у тебя сейчас повторяеться.
Выполняеться в случае если все отработало или если упала ошибка - подумай куда его можно перенести

2022-08-31 14:12 UTC, sergeyivanov1702 commented on src/init.js
>            });
этот код относиться к рендеру постов - он должен быть в соответствующей функции

2022-08-31 14:12 UTC, sergeyivanov1702 commented on src/init.js
> +                const objXml = parser(response.data.contents, i18nextInstance.t('errors.errorValidRSS'), state);
забыл удалить state из параметров, в parser у тебя уже 2 аргумента

2022-08-31 14:44 UTC, sergeyivanov1702 requested changes

2022-08-31 14:44 UTC, sergeyivanov1702 commented on src/parser.js
> +  const arrayXml = [];
поменяй имена, назови вещи своими именнами: тут у тебя уже массив постов - posts

2022-08-31 14:44 UTC, sergeyivanov1702 commented on src/parser.js
> +  const xmlObj = {
тут у тебя фид - feed.
И поменяй именна на соотвествующие в других файлах

2022-08-31 14:44 UTC, sergeyivanov1702 commented on src/render.js
> +export default function render(value, message) {
render(value, message) 
и value и message по сути своей message. В случае если форма валидная - ты используешь message, если невалидная ты используешь value. Можешь оставить один параметр message, 
вынести `elements.textFeedback.textContent = message;` из условий,
и немного поправить код в onChange в init.js

2022-09-01 09:53 UTC, AndreyKrymski commented on src/elementsDom.js
>  export default {
не понял что тут надо подисправить?

2022-09-01 09:55 UTC, AndreyKrymski commented on src/init.js
> +              });
не отработает там падает другая ошибка связанная с проммисом

2022-09-01 12:51 UTC, sergeyivanov1702 approved these changes

2022-09-01 12:51 UTC, sergeyivanov1702 commented on src/init.js
> +      const watcheState = onChange(state, (path, value) => {
(state, (path, value) - value можешь убрать. У тебя уже все должно быть в state.
Само value используеться очень редко.

2022-09-01 12:51 UTC, sergeyivanov1702 commented on src/isProcess.js
> +export default function renderProccess(value) {
измени имя аргумента с value на isProcess - будет понятнее

2022-09-02 07:26 UTC, merged